name: Update Version TXT on Release

on:
  release:
    types: [created]

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update version.txt
        run: |
          echo "${{ github.event.release.tag_name }}" | sed 's/^v//' > version.txt

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update version.txt to ${{ github.event.release.tag_name }}"
          file_pattern: version.txt
